/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PackageNameImport } from './routes/$packageName'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PackageNameRoute = PackageNameImport.update({
  id: '/$packageName',
  path: '/$packageName',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$packageName': {
      id: '/$packageName'
      path: '/$packageName'
      fullPath: '/$packageName'
      preLoaderRoute: typeof PackageNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$packageName': typeof PackageNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$packageName': typeof PackageNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$packageName': typeof PackageNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$packageName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$packageName'
  id: '__root__' | '/' | '/$packageName'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageNameRoute: typeof PackageNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageNameRoute: PackageNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$packageName"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$packageName": {
      "filePath": "$packageName.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
